### PR TITLE
Some fixes for Little Busters russian patch

### PR DESCRIPTION
**Pull request by xtsm**
I'm trying to resolve a couple of problems here.
- When a text window has a name and it's not in English, the text window appears empty and a UTF-8 decode error message appears in the console. This happens because the code that sets the window name lacks cp932->utf8 conversion. This is obviously by accident, fixed that.
- Invalid line breaks: <details></details>
There are two different parts of code responsible for line breaks. One of them is in rlBabel, another one thinks our font is monospaced and all russian characters are double width. For that reason it makes line breaks in inappropriate places because it thinks we're over the width (which is not true). rlBabel tries to fix the situation as the next character is being printed by setting the appropriate X coordinate but it's already too late. Disabling non-rlBabel line breaks seems to solve the problem so I've added a command line option for that. (Don't wanna just erase the code because it seems too dangerous and I can't test it on anything else for now.)

### CODE REVIEW

**Comment by eglaysher** [comment]
The asan and the non-ascii window processing make sense, I would merge those immediately if they were a separate patch.

Still sort of confused about what's going on with rlbabel in this case; it's been 8 years since I've looked at this code at all.

**Comment by xtsm** [comment]
Ok, I've removed the two commits about line breaks. Might make another PR about it later, do you need any explanations from me?

I might also make more PRs as I keep encountering problems while playing the VN. Sorry for bringing this stuff up, I didn't even expect these patches to ever get merged because I thought this project was completely dead...

**Comment by eglaysher** [comment]
I mean, the project basically is dead, though I am still around and I'm fine merging any obvious build fixes or straight up bugfixes that are obviously correct.

**Comment by eglaysher** [comment]
In the case of the rlBabel code, my very vague recollection since it's been well over a decade, was that all of that code was not really that well thought out and the integration was just massive hacking things together. On one hand, the way you added a flag really feels bad and I'd bet breaks Japanese games, but otoh, it's not like the rest of the code in the text layout system was well thought out.

**Comment by xtsm** [comment]
Wdym by "breaks Japanese games"? I was trying to add this flag in such a way that it changes absolutely nothing unless consciously turned on. Did I miss something?
When turned on, it definitely fixes *my* problem. The alternative solution would be to use standard msgothic font but it has square-shaped glyphs for cyrillic letters and reading that text makes me want to gouge my eyes out.

Otoh I didn't have a lot of time for thorough testing, maybe there would be more problems with this approach later in the game. The translation I'm currently using also looks pretty low-quality so maybe I'll just get an english one and call it a day...

Either way, thank you!

**Comment by eglaysher** [comment]
Sorry, when I said break Japanese games, my recollection is that it would blit one single extra Japanese fullwidth character past the bounding box of the text box.

**Comment by xtsm** [comment]
Maybe, idk. That's why it's a command line flag: unless the line breaks are bad, one shouldn't turn it on.

Of course ideally it should be solved by using the same line breaking code in rlbabel and text system, but that looks like too much work...

**Pull request merged**
